apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress-lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: svc
  resources:
    requests:
      storage: 5Gi
